# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatClasificacionPedido',
            fields=[
                ('n_clasificacion_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_clasificacion_pedido_nombre', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'cat_clasificacion_pedido',
            },
        ),
        migrations.CreateModel(
            name='CatEstado',
            fields=[
                ('n_estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_estado_nombre', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'cat_estado',
            },
        ),
        migrations.CreateModel(
            name='CatEstatus',
            fields=[
                ('n_estatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_estatus_nombre', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'cat_estatus',
            },
        ),
        migrations.CreateModel(
            name='DatClave',
            fields=[
                ('n_clave_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_clave_num', models.IntegerField()),
                ('n_clave_precioiva', models.FloatField()),
                ('c_clave_proceso', models.CharField(blank=True, max_length=45, null=True)),
                ('c_clave_presentacion', models.CharField(blank=True, max_length=45, null=True)),
                ('c_clave_descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('d_clave_fecha', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_clave',
            },
        ),
        migrations.CreateModel(
            name='DatContrato',
            fields=[
                ('n_contrato_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_proveedor_id', models.IntegerField()),
                ('n_partida_id', models.IntegerField()),
                ('c_contrato_monto', models.FloatField()),
                ('d_contrato_fechainicial', models.DateTimeField()),
                ('d_contrato_fechafinal', models.DateTimeField()),
                ('c_contrato_devengo', models.CharField(blank=True, max_length=45, null=True)),
                ('c_contrato_imgcontrato', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dat_contrato',
            },
        ),
        migrations.CreateModel(
            name='DatFactura',
            fields=[
                ('n_factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_factura_numero', models.IntegerField()),
                ('n_proveedor_id', models.IntegerField()),
                ('n_factura_penaconvencional', models.IntegerField(blank=True, null=True)),
                ('n_requisicion_id', models.IntegerField(blank=True, null=True)),
                ('n_factura_importe', models.FloatField(blank=True, null=True)),
                ('n_factura_total', models.FloatField(blank=True, null=True)),
                ('n_pedido_id', models.IntegerField()),
                ('n_factura_presupuesto', models.FloatField()),
                ('d_factura_fechaenvio', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_factura',
            },
        ),
        migrations.CreateModel(
            name='DatPartida',
            fields=[
                ('n_partida_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_partida_nombre', models.CharField(max_length=45)),
                ('n_clasificacion_pedido_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_partida',
            },
        ),
        migrations.CreateModel(
            name='DatPedido',
            fields=[
                ('n_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_pedido_numero', models.IntegerField()),
                ('n_pedido_importetotal', models.FloatField()),
                ('c_pedido_fuentefinanciera', models.CharField(max_length=45)),
                ('n_requisicion_id', models.IntegerField()),
                ('n_partida_id', models.IntegerField()),
                ('n_clave_id', models.IntegerField()),
                ('c_pedido_proceso', models.CharField(blank=True, max_length=45, null=True)),
                ('n_proveedor_id', models.IntegerField()),
                ('n_contrato_id', models.IntegerField()),
                ('n_proveedor_cantidad', models.IntegerField()),
                ('n_factura_id', models.IntegerField()),
                ('n_pedido_precio', models.FloatField()),
                ('n_pedido_totalclaveciva', models.FloatField()),
                ('d_pedido_fechaelaboracion', models.DateTimeField()),
                ('d_pedido_fechaentrega', models.DateTimeField()),
                ('n_estatus_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_pedido',
            },
        ),
        migrations.CreateModel(
            name='DatProveedor',
            fields=[
                ('n_proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_proveedor_nombre', models.CharField(max_length=45)),
                ('c_proveedor_nfiscal', models.CharField(max_length=45)),
                ('c_proveedor_domicilio', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_colonia', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_fax', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_rfc', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_cp', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('c_proveedor_email', models.CharField(blank=True, max_length=45, null=True)),
                ('n_proveedor_idrel', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_proveedor',
            },
        ),
        migrations.CreateModel(
            name='DatRequisicion',
            fields=[
                ('n_requisicion_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_requisicion_fecha', models.DateTimeField()),
                ('c_requisicion_solicitante', models.CharField(max_length=45)),
                ('c_requisicion_fuente', models.CharField(max_length=45)),
                ('c_requisicion_elabora', models.CharField(max_length=45)),
                ('c_requisicion_solicita', models.CharField(max_length=45)),
                ('c_requsicion_autoriza', models.CharField(max_length=45)),
                ('n_estado_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dat_requisicion',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
    ]
